Screen:
    MDLabel:
        text: app.load_data()
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    MDRaisedButton:
        text: 'Insert Data'
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        on_press:
            app.post_data()
    MDRaisedButton:
        text: 'Update Data'
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        on_press:
            app.put_data()
    MDRaisedButton:
        text: 'Delete Data'
        pos_hint: {'center_x': 0.5, 'center_y': 0.7}
        on_press:
            app.destroy_data()
    MDRaisedButton:
        text: 'Count : ' + str(app.get_count())
        pos_hint: {'center_x': 0.5, 'center_y': 0.4}
        
    MDTextFieldRound:
        # icon_left: "email"
        id: cityInput
        hint_text: "City Input"
        pos_hint: {'center_x': 0.5, 'center_y': 0.8}
    MDTextFieldRound:
        # icon_left: "email"
        id: cityID
        hint_text: "City ID"
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
    